[package]
name = "api-informatics-frs-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.3"
serde = "1.0.195"
serde_json = "1.0.111"
sqlx = { version = "0.7.3", features = ["runtime-tokio", "tls-native-tls", "mysql"] }
tokio = { version ="1.35.1", features = ["full"] }
tower = "0.4.13"
