# fly.toml app configuration file generated for api-informatics-frs-helper on 2024-01-08T22:11:50+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-informatics-frs-helper"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
